"""Safe, deterministic project materialization from an AgentSpec."""

from dataclasses import dataclass
from pathlib import PurePosixPath

from ..specs.agent_spec import AgentSpec


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str


class AgentProjectBuilder:
    """Generate a minimal runnable Python project skeleton for an agent."""

    def build(self, spec: AgentSpec) -> list[GeneratedFile]:
        errors = spec.validate()
        if errors:
            raise ValueError("Invalid AgentSpec: " + "; ".join(errors))

        package = self._package_name(spec.name)
        return [
            GeneratedFile(
                path=f"agents/{package}/__init__.py",
                content=f'"""Generated agent: {spec.name}."""\n',
            ),
            GeneratedFile(
                path=f"agents/{package}/agent.py",
                content=self._agent_module(spec),
            ),
            GeneratedFile(
                path=f"agents/{package}/SPEC.json",
                content=self._spec_json(spec),
            ),
            GeneratedFile(
                path=f"agents/{package}/README.md",
                content=self._readme(spec),
            ),
        ]

    @staticmethod
    def _package_name(name: str) -> str:
        normalized = "".join(ch.lower() if ch.isalnum() else "_" for ch in name)
        normalized = "_".join(part for part in normalized.split("_") if part)
        if not normalized:
            raise ValueError("Agent name must contain at least one alphanumeric character")
        return normalized

    @staticmethod
    def _agent_module(spec: AgentSpec) -> str:
        return f'''"""Generated runtime skeleton for {spec.name}."""

from typing import Any


class Agent:
    """{spec.purpose}"""

    name = {spec.name!r}
    role = {spec.role!r}

    def run(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Execute the generated agent.

        This first scaffold deliberately does not invent implementation logic.
        A model-backed builder can replace this method after specification review.
        """
        missing = [key for key in {spec.inputs!r} if key not in inputs]
        if missing:
            raise ValueError(f"Missing required inputs: {{missing}}")
        return {{"status": "not_implemented", "inputs": inputs}}
'''

    @staticmethod
    def _spec_json(spec: AgentSpec) -> str:
        import json

        return json.dumps(spec.to_dict(), indent=2, sort_keys=True) + "\n"

    @staticmethod
    def _readme(spec: AgentSpec) -> str:
        criteria = "\n".join(f"- {item}" for item in spec.acceptance_criteria)
        return f"""# {spec.name}

{spec.purpose}

**Role:** `{spec.role}`

## Acceptance criteria

{criteria}

This project was generated by AI Factory. The runtime is intentionally a
scaffold until a model-backed implementation is reviewed and tested.
"""
