"""Provider-neutral controller for publishing approved Factory changes.

The controller prepares an operation plan; the host application is responsible
for invoking the GitHub connector with the plan. Generated agent code never gets
GitHub credentials directly.
"""

from dataclasses import dataclass

from .changes import GitHubChangeSet
from .policy import GitHubAutomationPolicy


@dataclass(frozen=True)
class GitHubOperationPlan:
    branch: str
    commit_message: str
    pull_request_title: str
    pull_request_body: str
    files: tuple[str, ...]
    draft: bool = True


class GitHubController:
    """Turn a validated change-set into a safe GitHub operation plan."""

    def __init__(self, policy: GitHubAutomationPolicy | None = None) -> None:
        self.policy = policy or GitHubAutomationPolicy()

    def plan_publish(self, change_set: GitHubChangeSet) -> GitHubOperationPlan:
        change_set.validate(self.policy)
        files = tuple(file.path for file in change_set.files)
        return GitHubOperationPlan(
            branch=change_set.branch,
            commit_message=f"factory: {change_set.title}",
            pull_request_title=change_set.title,
            pull_request_body=(
                "Generated by AI Factory.\n\n"
                "This change was prepared under the Factory GitHub automation policy. "
                "Review CI and the diff before merging."
            ),
            files=files,
            draft=self.policy.require_pull_request,
        )
